# run the api with mongodb
version: "2"
services:
  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  # backup and restore data from volume
  # maximize portability by allowing multiple instances to share same data
  mongodata:
    image: tianon/true
    volumes:
      - /data/db